### ISSUE TITLE
[DODFMiner] Extrator XML

### ISSUE THREAD

**Issue by Lary15** [UnB-KnEDLe/viabilidade-tecnica#116]
O DODFMiner esta com problema na extração do XML. A execução fica em loop infinito para extrair um documento.  A execução do ato e título fica ordenada de forma estranha para atos recentes. 

- [x] Identificar o problema na extração de XML
- [x] Corrigir o bug
- [x] Criar casos de teste

**Comment by aliceborges42** [comment]
Pessoal, essa tarefa não é prioridade?  Ela não foi iniciada?
