### ISSUE TITLE
[DODFMiner] Paralelização da extração de atos

### ISSUE THREAD

**Issue by notopoloko** [UnB-KnEDLe/viabilidade-tecnica#135]
Alguns trechos de código realizam a extração de forma sequencial. Para melhorar o tempo de execução, esse processo pode ser feito de maneira paralelizada. Avaliar a extração paralelizada por diário e por ato.

**Comment by lpfgarcia** [comment]
![WhatsApp Image 2022-04-05 at 09 34 11](https://user-images.githubusercontent.com/5933174/161972849-3bee73a5-4c32-4fa9-98c5-4f91cd8e4afa.jpeg)
