### ISSUE TITLE
[DASH] Implementar a aba Pesquisa

### ISSUE THREAD

**Issue by lpfgarcia** [UnB-KnEDLe/viabilidade-tecnica#141]
## Contexto

Desenvolver a aba Pesquisa que realiza consultas no BD baseado em neo4j.

## Objetivo

* [x] Tela de login
* [x] Barra de rolagem para as queries
* [x] Trabalhar nos layout dos nós e arestas
* [x] Ajustar as informações que estão sendo mostradas nas relações
* [x] Verificar questão do timeout para algunas queries
* [x] Tornar visualização em tela cheia dentro da janela
* [x] Avaliar a implementação de um modelo em tela cheia "total"
* [x] Validar o retorno das consultas 
* [x] Analisar exportador de json na aba Neo4j

**Comment by Lary15** [comment]
[BUG Firefox] - "connection .... was interrupted while the page was loading"
Similar a https://github.com/socketio/socket.io/issues/2016
