### ISSUE TITLE
Finalizar relatório geral da Release 3

### ISSUE THREAD

**Issue by aliceborges42** [UnB-KnEDLe/viabilidade-tecnica#4]
- Carol - incluir parte de risco
- Thiago - colocar parte de extração
- Teo - colocar a parte do time named_entity_linking

Todos os professores devem revisar o documento e realizar as correções necessárias.

**Comment by Carolokimoto** [comment]
atualizando a parte dos riscos e do okr, mas o gerar o dashbord vi que vários times  não fizeram o preenchimento da última coluna com data de 23/6.
