### ISSUE TITLE
Relatório release 4

### ISSUE THREAD

**Issue by lpfgarcia** [UnB-KnEDLe/viabilidade-tecnica#62]
- [ ] Escrita usando overleaf (modelo: https://unbbr.sharepoint.com/sites/KnEDLe/Documentos%20Compartilhados/General/RELAT%C3%93RIO_BOLSISTAS/GRADUA%C3%87%C3%83O/Livia_Fonseca-20210618T115032Z-001/Livia_Fonseca/Release%202/LiviaFonseca_Report_december.zip)
- [ ] Revisão (avisar @lpfgarcia)
- [ ] Entrega

**Comment by notopoloko** [comment]
https://www.overleaf.com/1964294637sjbdnjwhhkpp

**Comment by vitorararuna** [comment]
Link para relatório https://www.overleaf.com/1715576982swqpmzpxxjgj

**Comment by jonatas1n** [comment]
Link para relatório: [https://pt.overleaf.com/2269689378rsbtxjrnxtwv](https://pt.overleaf.com/2269689378rsbtxjrnxtwv)

**Comment by felipexbds** [comment]
Link para relatório: https://www.overleaf.com/1439568658bgtjggyfspnb

**Comment by Lary15** [comment]
Link para relatório: https://www.overleaf.com/5366573259ccfzmtkdmzvb
