### ISSUE TITLE
Organizar planilha de OKR

### ISSUE THREAD

**Issue by aliceborges42** [UnB-KnEDLe/viabilidade-tecnica#7]

**Comment by aliceborges42** [comment]
- Colocar as porcentagens de cada objetivo e seu progresso
 - Gerar dashboard após todos os objetivos estarem devidamente preenchidos e seu progresso organizado

**Comment by Carolokimoto** [comment]
Planilha organizada, falta correção da Patrícia e objetivos do Time de Contratação
