### ISSUE TITLE
[DODFMinerAPI] Atualizar o BD v3

### ISSUE THREAD

**Issue by lpfgarcia** [UnB-KnEDLe/viabilidade-tecnica#71]
Com os modelos treinados, atualizar o BD (http://164.41.76.30/browser/).

**Comment by notopoloko** [comment]
- Substituição: Se testar com o nome **flavia caritas**, há 30 atos de substituição, porém no csv há ela substitui apenas 2 vezes e é substituída 1.
- Tornado sem efeito aposentadoria apresenta defeitos na parte de extração de entidades. 
- Nomeração efetiva apresenta informações erradas quando ocorre nomeação de várias pessoas.

**Comment by lpfgarcia** [comment]
@felipexbds conferir comentários do @notopoloko
