### ISSUE TITLE
[DASH] Ajustar/Corrigir bugs 

### ISSUE THREAD

**Issue by lpfgarcia** [UnB-KnEDLe/viabilidade-tecnica#73]
Ajustes necessários no DASH (http://164.41.76.30/dash/):

- [x] Erros de ortografia
- [x] Usar modelos NER
- [x] Pesquisa com timeout
- [x] Layout padronizado entre as abas
- [x] Pesquisa com comportamento correto
- [x] Ressaltar entidades (aba extrair atos)

**Comment by aliceborges42** [comment]
Atualizar a issue por favor @jonatas1n
