### ISSUE TITLE
[DODFMinerAPI] Sanitização das entidades

### ISSUE THREAD

**Issue by lpfgarcia** [UnB-KnEDLe/viabilidade-tecnica#76]
Implementar a sanitização na classe base nos scripts de importação.  Atualmente,  algumas entidades tem caracteres especiais ou traços, vírgulas e pontos. Isso impacta na criação das entidades do BD.

**Comment by notopoloko** [comment]
Feito com -> https://github.com/UnB-KnEDLe/DODFMinerAPI/commit/8ef81140c4f67f2d2f892528bb31c6d60578437d
