### ISSUE TITLE
[neo4j] Entidades defeituosas

### ISSUE THREAD

**Issue by lpfgarcia** [UnB-KnEDLe/viabilidade-tecnica#78]
O esquema do BD tem entidades e relações que podem ser melhoradas. O objetivo é ajustar continuamente o esquema do BD na release 5.

**Comment by vitorararuna** [comment]
- Revisar atos nos quais as relações estão sem o "act_id" (são poucos)
- Em alguns atos, o orgão tenta recuperar todos os atributos (essas informações estão realmente sendo extraídas ?)
    - devemos padronizar os atributos ?
- Atos de Exoneração com equívoco (sem relação de pessoa com matrícula & relação "EH_EXONERADA" com atributos estranhos)

**Comment by lpfgarcia** [comment]
@vitorararuna , essa issue  esta incluida na #96?
