### ISSUE TITLE
[DODFMiner] Extração de título

### ISSUE THREAD

**Issue by lpfgarcia** [UnB-KnEDLe/viabilidade-tecnica#87]
Ajustar a extração de título/data para diferentes DODFs

**Comment by Lary15** [comment]
## Mudanças feitas na branch de fix/title-extractor

- Update - Striping text on extract_structure
Commit insere metodo strip no titulo a ser comparado pelo loop do extract_structure

- Update - Using PyMuPDF version 1.19.1
Atualiza versão do PyMuPDF, mas planejo trocar para a versão 1.19.14, que é a mais recente.

- Fix - Premature section capture
Introduz uma possível solução para DODF's com Sumário sendo capturado por texto. O Sumário contém as palavras SEÇÃO I, SEÇÃO II, SEÇÃO III. Isso é problemático para a construção da estrutura dividida por seções.

- Update - Suppressing images on block extraction
Mudança leve da chamada do metódo de extração de blocos para não retornar imagens por padrão. Alteração deve ser feita pela mudança de versão do PyMu.

- Update - Not raising error on _mount_json anymore
Suprimindo erro no método da classe `ExtractorTitleSubtitle` relacionado à posição de elementos no atributo `self._titles_subtitles`
