### ISSUE TITLE
[DODFMiner] Indução de modelos de segmentação

### ISSUE THREAD

**Issue by lpfgarcia** [UnB-KnEDLe/viabilidade-tecnica#90]
## Contexto

Indução de modelos estado da arte para segmentação de atos de pessoal.

## Objetivo

* [x] Ajustar os modelos atuais para considerar sentenças e não palavras. 
* [x] Selecionar subconjunto de técnicas estado da arte
* [ ] Induzir os modelos
* [ ] Validar modelos

**Comment by aliceborges42** [comment]
Pessoal, como ta essa issue? ela ta ha um tempo no to do porém sem sprint
